// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GS_IntroWindow","status":false,"description":"Muestra una pantalla de login con usuario y contraseña que se validan con Google Sheets al iniciar el juego.","parameters":{}},
{"name":"GS_StorageManager","status":false,"description":"Sistema de guardado en Google Sheets con autenticación [v2.0]","parameters":{"Script URL":"https://script.google.com/macros/s/SCRIPT_ID/exec","Mostrar Login":"true"}},
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"CustomLogo","status":false,"description":"Shows RPG Maker and user logos at the start of the game.","parameters":{"logo1":"","logo1ImageName":"MadeWithMv","logo1Skippable":"true","logo1Coordinate":"","logo1X":"408","logo1Y":"312","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"OpenCustomWindow","status":false,"description":"[v1.0] Abre una ventana personalizada con un comando de plugin.","parameters":{}},
{"name":"VidaHUD","status":false,"description":"Muestra una variable como \"Tarea_2\" junto al Oro en el menú principal.","parameters":{"Vida Variable ID":"1"}},
{"name":"MinijuegoBase","status":true,"description":"[v1.0] Minijuego base con comando de activación desde evento. 🔧","parameters":{}},
{"name":"DiarioDeCampo","status":false,"description":"Diario de Campo con imagen de fondo y caja de texto personalizable. Muestra texto al interactuar con evento \"EV003\". [Luis]","parameters":{}},
{"name":"LibretaPersonal","status":true,"description":"Agrega un botón \"Libreta\" al menú con tres botones: Matriz de Habitantes, Indicaciones y Variables. Muestra ventana personalizada.","parameters":{}},
{"name":"NombreYTextoExtendido","status":false,"description":"Aumenta el límite de líneas por mensaje y muestra el nombre del hablante debajo del cuadro de texto. [v1.2] (corregido)","parameters":{}},
{"name":"MedidasF","status":true,"description":"[v2.0] Minijuego de Asociación de Porcentajes - 18 cajas","parameters":{}},
{"name":"ClasiFVariables","status":true,"description":"[v2.0] Minijuego de Asociación de Porcentajes - 18 cajas","parameters":{}},
{"name":"TiposVigilancia","status":true,"description":"[v2.0] Minijuego de Asociación de Porcentajes - 18 cajas","parameters":{}},
{"name":"Triadados","status":true,"description":"[v1.0] Minijuego base con comando de activación desde evento.","parameters":{}},
{"name":"DefCasofinal","status":true,"description":"[v2.0] Minijuego de Asociación de Porcentajes - 18 cajas","parameters":{}},
{"name":"Determinantes","status":true,"description":"[v2.0] Minijuego de Asociación de Porcentajes - 18 cajas","parameters":{}},
{"name":"MedidasTendencia","status":true,"description":"[v2.0] Minijuego de Asociación de Porcentajes - 18 cajas","parameters":{}},
{"name":"MedidasDispersion","status":true,"description":"[v2.0] Minijuego de Asociación de Porcentajes - 18 cajas","parameters":{}},
{"name":"TareaTres","status":false,"description":"","parameters":{}},
{"name":"TareaDos","status":false,"description":"","parameters":{}},
{"name":"MultiHUD","status":true,"description":"Muestra las variables de Tarea 2, Tarea 3 y Oro en el menú principal.","parameters":{"Tarea2 Variable ID":"4","Tarea3 Variable ID":"160"}},
{"name":"PoblacionMuestra","status":true,"description":"[v2.0] Minijuego de Asociación de Porcentajes - 18 cajas","parameters":{}},
{"name":"CondicionesVidaDeterminantes","status":true,"description":"[v2.0] Minijuego de Asociación de Porcentajes - 18 cajas","parameters":{}},
{"name":"NivelesDeprevwncionSalud","status":true,"description":"[v1.0] Minijuego base con comando de activación desde evento.","parameters":{}},
{"name":"CheckConexionGS","status":true,"description":"","parameters":{}},
{"name":"ConnetGS","status":false,"description":"Guardado en Google Sheets mediante API externa (Apps Script) - v1.0","parameters":{}},
{"name":"PruebaConetGS","status":true,"description":"Guardado en Google Sheets mediante API externa (Apps Script) - v1.0","parameters":{}}
];
